api_platform:
    title: Hello API Platform
    version: 1.0.0
    formats:
        jsonld:   ['application/ld+json']
        json:     ['application/json']
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
    eager_loading:
        max_joins: 60 
        force_eager: false
